# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragioneSociale', models.CharField(db_index=True, max_length=100, null=True)),
                ('piva', models.CharField(max_length=100, null=True)),
                ('indirizzo', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=100, null=True)),
                ('data', models.DateField(null=True)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionale.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('prezzo', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
