# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fattura',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionale.Prodotto'),
        ),
    ]
