# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0002_auto_20191119_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fattura',
            name='prodotto',
        ),
        migrations.AddField(
            model_name='fattura',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionale.Cliente'),
        ),
        migrations.AddField(
            model_name='fattura',
            name='Prodotto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionale.Prodotto'),
        ),
    ]
